<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trainee Export</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div>
        <table>
            <tr>
                @php
                    $colspan = 8;
                @endphp
            <tr>
                <th style="font-weight: bold; font-size: 24px;" colspan="{{ $colspan }}">
                    Her Power Trainee List
                </th>
            </tr>
            <tr>
                <th style="" colspan="{{ $colspan }}">
                    Generated By: {{ $authProfile['KnownAs'] ?? '' }},
                    Generated At: {{ Carbon\Carbon::now()->format('d/m/Y h:i:s A') }}
                </th>
            </tr>

            <tr>
                <th style="font-weight: bold;" colspan="{{ $colspan }}">
                    Batch Code: {{ $batch['batchCode'] ?? '' }}
                </th>
            </tr>
            <tr>
                <th style="font-weight: bold;" colspan="{{ $colspan }}">
                    Course Name: {{ $batch['get_training']['title']['Name'] ?? '' }}
                </th>
            </tr>

            <tr>
                <th style="font-weight: bold; "colspan="{{ $colspan }}">
                    Address: {{ $batch['GEOLocation'] ?? '' }}
                </th>
            </tr>
            <tr>
                <th style="font-weight: bold; "colspan="{{ $colspan }}">
                    Total Class Days:{{ $batch['duration'] ?? '' }} Days
                </th>
            </tr>
            <tr>
                <th style="font-weight: bold; "colspan="{{ $colspan }}">
                    Total :{{ count($batch['trainees'] ?? []) }}
                </th>
            </tr>

            <tr>
                <th style="" colspan="{{ $colspan }}">

                </th>
            </tr>
        </table>

        <table>
            <thead>
                <tr>
                    <th style="font-weight: bold; border: 1px solid #000;">Sl. No.</th>
                    <th style="font-weight: bold; border: 1px solid #000;">Full Name</th>
                    <th style="font-weight: bold; border: 1px solid #000;">Email</th>
                    <th style="font-weight: bold; border: 1px solid #000;">NID </th>
                    <th style="font-weight: bold; border: 1px solid #000;">Contact </th>
                    <th style="font-weight: bold; border: 1px solid #000;">Father's Name</th>
                    <th style="font-weight: bold; border: 1px solid #000;">Mother's Name</th>
                    <th style="font-weight: bold; border: 1px solid #000;">Present Address</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($batch['trainees'] as $trainee)
                    <tr>
                        <td style="border: 1px solid #000;">{{ $loop->iteration }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['KnownAs'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['Email'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['NID'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['Phone'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['FatherNameBangla'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['MotherNameBangla'] ?? '' }}</td>
                        <td style="border: 1px solid #000;">{{ $trainee['profile']['address_present'] ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
